/** 
JOINS
1.INNER JOIN 
2.LEFF JOIN
3.RIGHT JOIN
4.FULL JOIN

**/

USE NORTHWND;

SELECT C.CategoryID, 
C.CategoryName,
P.ProductID,
P.ProductName,
P.UnitPrice,
P.UnitsInStock,
(P.UnitPrice * P.UnitsInStock)
AS [PRECIO INVENTARIO]
FROM Categories AS C
INNER JOIN Products AS P
ON C.CategoryID = P.CategoryID
WHERE C.CategoryID=9;

/*
FLUJO LOGICO DE EJECUCUION DE SQL
1.FROM 
2.JOIN 
3.WHERE
4.GROUP BY
5.HAVING
6.SELECT
7.DISTING
8.ORDER BY 
*/

--SELECCIONAR LOS CLIENTES QUE HAYAN REALIZADO 
--MAS DE 10 PEDIDOS 


SELECT Customerid, COUNT(*) AS [NUMERO DE ORDENES]
FROM Orders
GROUP BY CustomerID
HAVING COUNT(*) >10
ORDER BY 2 DESC;

SELECT Customerid, COUNT(*) AS [NUMERO DE ORDENES]
FROM Orders
WHERE ShipCountry IN ('GERMANY', 'FRANCE', 'BRAZIL')
GROUP BY CustomerID, ShipCountry
HAVING COUNT(*) >10
ORDER BY 2 DESC;

SELECT C.CompanyName, COUNT(*) AS [NUMERO DE ORDENES]
FROM Orders AS O
INNER JOIN
Customers AS C
ON O.CustomerID = C.CustomerID
GROUP BY C.CompanyName
HAVING COUNT(*) > 10
ORDER BY 2 DESC;

--SELECCIONAR LOS EMPLEADOS QUE HAYAN GESTIONADO PEDIDOS POR UN TOTAL
--SUPERIOR A 100000 EN VENTAS
--MOSTRAR EL ID DEL EMPLEADO Y EL NOMBRE Y EL TOTAL DE COMPRAS

SELECT
	CONCAT (E.FirstName,' ',E.LastName) AS [NOMBRE COMPLETO], 
	ROUND (SUM(OD.Quantity * OD.UnitPrice * (1-OD.Discount)), 2) AS [IMPORTE]
FROM Employees AS E
INNER JOIN Orders AS O
ON E.EmployeeID = O.EmployeeID
INNER JOIN [Order Details] AS OD
ON O.OrderID = OD.OrderID
GROUP BY E.FirstName, E.LastName
HAVING SUM(OD.Quantity * OD.UnitPrice * (1-OD.Discount)) > 100000
ORDER BY [IMPORTE] DESC;

--SELECCIONAR EL PRECIO M�XIMO DE PRODUCTOS POR CATEGORIA
--PERO SOLO SI LA SUNA DE UNIDADES ES MENOR A 200 Y ADEMAS
--QUE NO ESTEN DESCONTINUADOS


SELECT 
	C.CategoryID,
	C.CategoryName,
	P.ProductName,
	MAX(P.UnitPrice) AS [PRECIO MAXIMO]
FROM Products AS P
INNER JOIN Categories AS C
ON P.CategoryID = C.CategoryID
WHERE P.Discontinued = 0
GROUP BY C.CategoryID,
		C.CategoryName,
		P.ProductName
HAVING SUM(P.UnitsInStock) < 200
ORDER BY CategoryName, P.ProductName DESC;

